# Generated by Django 3.0.8 on 2020-08-03 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200803_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_post',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=1200, upload_to='photo_user'),
            preserve_default=False,
        ),
    ]
